import Link from "next/link";
import { updateAgencyLifecycle } from "@/app/admin/agencies/actions";
import { AdminShell } from "@/components/admin/admin-shell";
import { AuthMessage } from "@/components/auth/auth-message";
import { PageHeading } from "@/components/dashboard/page-heading";
import { getPlatformAdmin } from "@/lib/platform-admin";

type Detail = { agency: { id:string;name:string;slug:string;email:string|null;phone:string|null;website:string|null;lifecycle_status:string;plan_code:string;created_at:string;trial_ends_at:string|null }; counts: Record<string,number>; usage: Array<{month_start:string;ai_conversations:number;ai_input_tokens:number;ai_output_tokens:number;estimated_ai_cost_usd:number;whatsapp_messages:number;storage_bytes:number}>; integrations:Array<{provider:string;status:string;connected_at:string|null}> };
export default async function AgencyDetailPage({ params, searchParams }: { params:Promise<{id:string}>; searchParams:Promise<{error?:string;message?:string}> }) {
  const { user, supabase } = await getPlatformAdmin(); const { id } = await params; const messages = await searchParams;
  const { data, error } = await supabase.rpc("get_platform_agency_detail", { target_agency_id:id });
  if (error || !data) return <AdminShell currentPath="/admin/agencies" userEmail={user.email}><p>Agency-ga lama helin.</p></AdminShell>;
  const d = data as Detail; const currentUsage=d.usage[0];
  return <AdminShell currentPath="/admin/agencies" userEmail={user.email}><div className="mx-auto max-w-7xl space-y-7"><Link className="text-sm font-bold text-emerald-700" href="/admin/agencies">← Agencies</Link><PageHeading eyebrow="Agency account" title={d.agency.name} description={`${d.agency.slug} · ${d.agency.email || "Email ma jiro"}`} /><AuthMessage {...messages} />
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{Object.entries(d.counts).map(([k,v])=><article className="rounded-2xl border bg-white p-5" key={k}><p className="text-xs font-bold uppercase text-slate-500">{k}</p><p className="mt-2 text-3xl font-black">{v}</p></article>)}</section>
    <section className="grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border bg-white p-6"><h2 className="font-black">Account control</h2><form action={updateAgencyLifecycle} className="mt-5 space-y-4"><input name="agency_id" type="hidden" value={id}/><label className="block text-sm font-bold">Status<select className="mt-2 w-full rounded-xl border px-3 py-2" defaultValue={d.agency.lifecycle_status} name="lifecycle_status">{["trial","active","suspended","archived"].map(x=><option key={x}>{x}</option>)}</select></label><label className="block text-sm font-bold">Plan<select className="mt-2 w-full rounded-xl border px-3 py-2" defaultValue={d.agency.plan_code} name="plan_code">{["starter","pro","enterprise"].map(x=><option key={x}>{x}</option>)}</select></label><button className="rounded-xl bg-slate-950 px-5 py-3 font-bold text-white">Kaydi isbeddelka</button></form></article>
    <article className="rounded-2xl border bg-white p-6"><h2 className="font-black">Usage bishan</h2>{currentUsage?<dl className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-slate-500">AI conversations</dt><dd className="text-xl font-black">{currentUsage.ai_conversations}</dd></div><div><dt className="text-slate-500">Estimated AI cost</dt><dd className="text-xl font-black">${Number(currentUsage.estimated_ai_cost_usd).toFixed(4)}</dd></div><div><dt className="text-slate-500">Input tokens</dt><dd className="font-bold">{currentUsage.ai_input_tokens}</dd></div><div><dt className="text-slate-500">Output tokens</dt><dd className="font-bold">{currentUsage.ai_output_tokens}</dd></div></dl>:<p className="mt-4 text-sm text-slate-500">Usage wali lama diiwaangelin.</p>}<h3 className="mt-7 font-bold">Integrations</h3><div className="mt-3 space-y-2">{d.integrations.length?d.integrations.map(i=><p className="flex justify-between rounded-xl bg-slate-50 px-3 py-2 text-sm" key={i.provider}><span>{i.provider}</span><strong>{i.status}</strong></p>):<p className="text-sm text-slate-500">Integration ma jiro.</p>}</div></article></section>
  </div></AdminShell>;
}
