import Link from "next/link";

import { logout } from "@/app/(auth)/actions";
import { cancelFollowUp, createFollowUpRule, retryFollowUp, scheduleFollowUp, setCustomerOptOut, toggleFollowUpRule } from "@/app/follow-ups/actions";
import { AuthMessage } from "@/components/auth/auth-message";
import { EmptyState } from "@/components/dashboard/empty-state";
import { PageHeading } from "@/components/dashboard/page-heading";
import { AppShell } from "@/components/layout/app-shell";
import { getAgencyWorkspace } from "@/lib/agency-workspace";

const badge: Record<string, string> = { pending: "bg-sky-100 text-sky-800", processing: "bg-amber-100 text-amber-800", sent: "bg-emerald-100 text-emerald-800", cancelled: "bg-slate-100 text-slate-600", failed: "bg-rose-100 text-rose-800", opted_out: "bg-violet-100 text-violet-800" };
const input = "mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-emerald-500";

export default async function FollowUpsPage({ searchParams }: { searchParams: Promise<{ error?: string; message?: string; view?: string }> }) {
  const { supabase, user, membership, agency } = await getAgencyWorkspace();
  const params = await searchParams;
  const [{ data: rules }, { data: followUps }, { data: leads }, { data: customers }] = await Promise.all([
    supabase.from("follow_up_rules").select("*").eq("agency_id", agency.id).order("created_at", { ascending: false }),
    supabase.from("follow_ups").select("id, lead_id, channel, scheduled_for, message_template, status, attempt_count, max_attempts, sequence_no, sent_at, last_error").eq("agency_id", agency.id).order("scheduled_for", { ascending: false }).limit(100),
    supabase.from("leads").select("id, customer_id, name, phone, status").eq("agency_id", agency.id).not("status", "in", "(won,lost)").order("created_at", { ascending: false }),
    supabase.from("customers").select("id, name, phone, follow_up_opted_out").eq("agency_id", agency.id).order("updated_at", { ascending: false }).limit(100),
  ]);
  const leadMap = new Map(leads?.map((item) => [item.id, item.name || item.phone || "Lead aan magac lahayn"]));
  const canManageRules = ["owner", "admin", "manager"].includes(membership.role);
  const stats = ["pending", "sent", "failed", "opted_out"].map((status) => ({ status, count: followUps?.filter((item) => item.status === status).length ?? 0 }));
  const activeView = params.view ?? "scheduled";
  const visibleFollowUps = followUps?.filter((item) => activeView === "completed" ? item.status === "sent" : activeView === "failed" ? item.status === "failed" : ["pending", "processing"].includes(item.status));
  return <AppShell agencyName={agency.name} currentPath="/follow-ups" logoutAction={logout} userEmail={user.email}><div className="mx-auto w-full max-w-7xl space-y-8">
    <PageHeading eyebrow="Automation" title="Follow-ups" description="Jadwal fariimo, samee rules, oo ixtiraam customer opt-out si aan spam loo dirin." />
    <AuthMessage error={params.error} message={params.message} />
    <section className="grid grid-cols-2 gap-3 sm:grid-cols-4">{stats.map((item) => <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm" key={item.status}><p className="text-xs font-bold capitalize text-slate-500">{item.status.replace("_", " ")}</p><p className="mt-2 text-2xl font-black text-slate-950">{item.count}</p></div>)}</section>
    <nav className="flex flex-wrap gap-2"><Link className={`rounded-xl px-4 py-2 text-sm font-bold ${activeView === "scheduled" ? "bg-slate-950 text-white" : "bg-white"}`} href="/follow-ups?view=scheduled">Scheduled</Link><Link className={`rounded-xl px-4 py-2 text-sm font-bold ${activeView === "completed" ? "bg-emerald-500 text-slate-950" : "bg-white"}`} href="/follow-ups?view=completed">Completed</Link><Link className={`rounded-xl px-4 py-2 text-sm font-bold ${activeView === "failed" ? "bg-rose-600 text-white" : "bg-white"}`} href="/follow-ups?view=failed">Failed queue</Link><span className="rounded-xl bg-white px-4 py-2 text-sm font-bold">Opt-outs ↓</span></nav>

    <section className="grid gap-6 xl:grid-cols-2">
      <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-lg font-bold text-slate-950">Follow-up manual ah</h2><p className="mt-1 text-sm text-slate-500">Dooro lead, fariin iyo waqtiga la diri doono.</p><form action={scheduleFollowUp} className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Lead<select className={input} name="lead_id" required><option value="">Dooro lead</option>{leads?.map((lead) => <option key={lead.id} value={lead.id}>{lead.name || lead.phone || "Lead aan magac lahayn"}</option>)}</select></label><label className="text-sm font-semibold text-slate-700">Channel<select className={input} name="channel"><option value="website">Website</option><option value="whatsapp">WhatsApp</option><option value="phone">Phone</option><option value="manual">Dashboard reminder</option></select></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Waqtiga<input className={input} name="scheduled_for" required type="datetime-local" /></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Fariinta<textarea className={`${input} min-h-24`} name="message_template" placeholder="Asc, ma weli xiisaynaysaa property-gii?" required /></label><button className="w-fit rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white" type="submit">Jadwal follow-up</button></form></div>

      <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-lg font-bold text-slate-950">Automation rule cusub</h2><p className="mt-1 text-sm text-slate-500">Rule-ku wuxuu leads cusub u sameeyaa follow-ups soo noqnoqda.</p>{canManageRules ? <form action={createFollowUpRule} className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Magaca rule-ka<input className={input} name="name" placeholder="Lead cusub — 2 saac" required /></label><label className="text-sm font-semibold text-slate-700">Delay (daqiiqo)<input className={input} defaultValue="120" max="43200" min="5" name="delay_minutes" required type="number" /></label><label className="text-sm font-semibold text-slate-700">Ugu badnaan<select className={input} defaultValue="2" name="max_follow_ups">{[1,2,3,4,5].map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label className="text-sm font-semibold text-slate-700">Channel<select className={input} name="channel"><option value="website">Website</option><option value="whatsapp">WhatsApp</option><option value="manual">Dashboard</option></select></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Template<textarea className={`${input} min-h-24`} name="message_template" required /></label><button className="w-fit rounded-xl bg-emerald-500 px-4 py-2.5 text-sm font-bold text-slate-950" type="submit">Abuur rule</button></form> : <p className="mt-5 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">Owner, admin ama manager ayaa rules samayn kara.</p>}</div>
    </section>

    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold text-slate-950">Automation rules</h2><p className="mt-1 text-sm text-slate-500">Enable ama pause garee rules-ka agency-ga.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">{rules?.length ?? 0} rules</span></div>{rules?.length ? <div className="mt-5 grid gap-3 md:grid-cols-2">{rules.map((rule) => <article className="rounded-2xl border border-slate-200 p-4" key={rule.id}><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold text-slate-950">{rule.name}</h3><p className="mt-1 text-xs text-slate-500">{rule.delay_minutes} daqiiqo · {rule.channel} · max {rule.max_follow_ups}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${rule.is_enabled ? "bg-emerald-100 text-emerald-800" : "bg-slate-100 text-slate-500"}`}>{rule.is_enabled ? "Active" : "Paused"}</span></div><p className="mt-3 line-clamp-2 text-sm text-slate-600">{rule.message_template}</p>{canManageRules ? <form action={toggleFollowUpRule} className="mt-4"><input name="rule_id" type="hidden" value={rule.id} /><input name="enabled" type="hidden" value={String(!rule.is_enabled)} /><button className="rounded-lg border border-slate-300 px-3 py-1.5 text-xs font-bold text-slate-700">{rule.is_enabled ? "Pause" : "Enable"}</button></form> : null}</article>)}</div> : <div className="mt-5"><EmptyState title="Rule ma jiro" description="Samee rule-ka ugu horreeya si leads cusub loo xasuusiyo." /></div>}</section>

    <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-5"><h2 className="text-lg font-bold text-slate-950">{activeView === "completed" ? "Completed" : activeView === "failed" ? "Failed queue" : "Scheduled queue"}</h2><p className="mt-1 text-sm text-slate-500">Worker-ku wuxuu diraa fariimaha, fashilkana retry/backoff ayuu sameeyaa ilaa max attempts.</p></div>{visibleFollowUps?.length ? <div className="divide-y divide-slate-100">{visibleFollowUps.map((item) => <article className="grid gap-3 p-5 md:grid-cols-[1fr_1fr_auto] md:items-center" key={item.id}><div><p className="font-bold text-slate-950">{leadMap.get(item.lead_id) || "Lead"}</p><p className="mt-1 line-clamp-1 text-xs text-slate-500">{item.message_template}</p>{item.last_error ? <p className="mt-2 text-xs font-semibold text-rose-700">{item.last_error}</p> : null}</div><div><p className="text-sm font-semibold text-slate-700">{new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.scheduled_for))}</p><p className="mt-1 text-xs text-slate-400">{item.channel} · attempt {item.attempt_count}/{item.max_attempts}</p></div><div className="flex items-center gap-2"><span className={`rounded-full px-3 py-1 text-xs font-bold ${badge[item.status] ?? "bg-slate-100"}`}>{item.status}</span>{item.status === "pending" ? <form action={cancelFollowUp}><input name="follow_up_id" type="hidden" value={item.id} /><button className="text-xs font-bold text-rose-700">Cancel</button></form> : null}{item.status === "failed" ? <form action={retryFollowUp}><input name="follow_up_id" type="hidden" value={item.id} /><button className="rounded-lg bg-rose-600 px-3 py-1.5 text-xs font-bold text-white">Retry now</button></form> : null}</div></article>)}</div> : <div className="p-6"><EmptyState title="Queue-gu waa madhan yahay" description="Wax item ah kuma jiro qaybtaan." /></div>}</section>

    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-lg font-bold text-slate-950">Customer opt-out</h2><p className="mt-1 text-sm text-slate-500">Customer-ku markuu joojiyo fariimaha, pending follow-ups oo dhan waa la xiraa.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{customers?.map((customer) => <article className="flex items-center justify-between gap-3 rounded-2xl border border-slate-200 p-4" key={customer.id}><div className="min-w-0"><p className="truncate font-bold text-slate-900">{customer.name || customer.phone || "Customer"}</p><p className={`mt-1 text-xs font-semibold ${customer.follow_up_opted_out ? "text-rose-700" : "text-emerald-700"}`}>{customer.follow_up_opted_out ? "Opted out" : "Follow-up allowed"}</p></div><form action={setCustomerOptOut}><input name="customer_id" type="hidden" value={customer.id} /><input name="opted_out" type="hidden" value={String(!customer.follow_up_opted_out)} /><button className="rounded-lg border border-slate-300 px-2.5 py-1.5 text-xs font-bold text-slate-700">{customer.follow_up_opted_out ? "Allow" : "Opt out"}</button></form></article>)}</div></section>
  </div></AppShell>;
}
