import { updateAgencyLifecycle } from "@/app/admin/agencies/actions";
import { AuthMessage } from "@/components/auth/auth-message";
import { AdminShell } from "@/components/admin/admin-shell";
import { PageHeading } from "@/components/dashboard/page-heading";
import { getPlatformAdmin } from "@/lib/platform-admin";

export default async function AdminAgenciesPage({ searchParams }: { searchParams: Promise<{ error?: string; message?: string }> }) {
  const { user, admin } = await getPlatformAdmin(); const params = await searchParams;
  const { data: agencies } = await admin.from("agencies").select("id, name, slug, email, lifecycle_status, plan_code, trial_ends_at, created_at").order("created_at", { ascending: false });
  return <AdminShell currentPath="/admin/agencies" userEmail={user.email}><div className="mx-auto max-w-7xl space-y-7"><PageHeading eyebrow="Tenant management" title="Agencies" description="Eeg plan-ka oo maamul lifecycle-ka tenant kasta adigoon gelin xogtiisa gaarka ah." /><AuthMessage error={params.error} message={params.message} /><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{agencies?.length ? <div className="divide-y divide-slate-100">{agencies.map((agency) => <article className="grid gap-4 p-5 lg:grid-cols-[1fr_auto] lg:items-center" key={agency.id}><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold text-slate-950">{agency.name}</h2><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-600">{agency.lifecycle_status}</span><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700">{agency.plan_code}</span></div><p className="mt-1 text-xs text-slate-500">{agency.slug} · {agency.email || "Email ma jiro"} · {new Date(agency.created_at).toLocaleDateString()}</p></div><form action={updateAgencyLifecycle} className="flex flex-wrap items-center gap-2"><input name="agency_id" type="hidden" value={agency.id} /><select className="rounded-xl border border-slate-300 px-3 py-2 text-sm" defaultValue={agency.lifecycle_status} name="lifecycle_status">{["trial","active","suspended","archived"].map((status) => <option key={status}>{status}</option>)}</select><select className="rounded-xl border border-slate-300 px-3 py-2 text-sm" defaultValue={agency.plan_code} name="plan_code">{["starter","pro","enterprise"].map((plan) => <option key={plan}>{plan}</option>)}</select><button className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-bold text-white">Kaydi</button></form></article>)}</div> : <p className="p-8 text-sm text-slate-500">Agency ma jiro.</p>}</section></div></AdminShell>;
}
