import Link from "next/link";
import { notFound } from "next/navigation";
import { logout } from "@/app/(auth)/actions";
import { assignConversation, sendAgentMessage, setConversationMode } from "@/app/conversations/actions";
import { AuthMessage } from "@/components/auth/auth-message";
import { AppShell } from "@/components/layout/app-shell";
import { getAgencyWorkspace } from "@/lib/agency-workspace";
import { rankProperties } from "@/lib/matching/property-matcher";

const statusStyle: Record<string, string> = { ai_active: "bg-sky-100 text-sky-800", human_active: "bg-amber-100 text-amber-800", closed: "bg-slate-100 text-slate-600", open: "bg-emerald-100 text-emerald-800" };

export default async function ConversationDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; message?: string }> }) {
  const { supabase, user, membership, agency } = await getAgencyWorkspace(); const { id } = await params; const query = await searchParams;
  const [{ data: conversation }, { data: messages }, { data: inbox }, { data: properties }, { data: members }] = await Promise.all([
    supabase.from("conversations").select("id,channel,status,created_at,lead_id,assigned_agent_id,leads(*)").eq("agency_id", agency.id).eq("id", id).maybeSingle(),
    supabase.from("messages").select("id,sender_type,message,created_at").eq("agency_id", agency.id).eq("conversation_id", id).order("created_at"),
    supabase.from("conversations").select("id,channel,status,updated_at,leads(name,phone,email)").eq("agency_id", agency.id).order("updated_at", { ascending: false }).limit(50),
    supabase.from("properties").select("id,title,purpose,status,district,price,currency,bedrooms,property_type,furnished").eq("agency_id", agency.id).eq("status", "available"),
    supabase.from("agency_members").select("id,user_id,role,availability").eq("agency_id", agency.id).eq("is_active", true),
  ]);
  if (!conversation) notFound();
  const memberUserIds = members?.map((member) => member.user_id) ?? [];
  const { data: memberProfiles } = memberUserIds.length ? await supabase.from("user_profiles").select("id,full_name").in("id", memberUserIds) : { data: [] };
  const memberNameByUserId = new Map(memberProfiles?.map((profile) => [profile.id, profile.full_name]));
  const relation = conversation.leads as Record<string, unknown> | Record<string, unknown>[] | null; const lead = (Array.isArray(relation) ? relation[0] : relation) as Record<string, unknown> | null;
  const matches = lead ? rankProperties({ purpose: lead.purpose as string | null, district: lead.district as string | null, budget_min: lead.budget_min === null ? null : Number(lead.budget_min), budget_max: lead.budget_max === null ? null : Number(lead.budget_max), bedrooms: lead.bedrooms as number | null, property_type: lead.property_type as string | null, furnished: lead.furnished as boolean | null }, (properties ?? []).map((property) => ({ ...property, price: Number(property.price) }))).slice(0, 3) : [];
  const { data: viewings } = conversation.lead_id ? await supabase.from("viewings").select("id,starts_at,status,properties(title)").eq("agency_id", agency.id).eq("lead_id", conversation.lead_id).order("starts_at", { ascending: false }).limit(3) : { data: [] };
  return <AppShell agencyName={agency.name} currentPath="/conversations" logoutAction={logout} userEmail={user.email}><div className="grid w-full min-w-0 gap-4 xl:grid-cols-[18rem_minmax(0,1fr)_20rem]">
    <aside className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-4"><p className="text-xs font-black tracking-wide text-emerald-700 uppercase">Inbox</p><h1 className="mt-1 text-xl font-black">Conversations</h1></div><div className="max-h-[75vh] overflow-y-auto">{inbox?.map((item) => { const r = item.leads as { name?: string|null; phone?: string|null; email?: string|null } | { name?: string|null; phone?: string|null; email?: string|null }[] | null; const l = Array.isArray(r) ? r[0] : r; return <Link className={`block border-b border-slate-100 p-4 hover:bg-slate-50 ${item.id === id ? "bg-emerald-50" : ""}`} href={`/conversations/${item.id}`} key={item.id}><div className="flex items-start justify-between gap-2"><p className="truncate text-sm font-bold">{l?.name || l?.phone || l?.email || "Website visitor"}</p><span className={`h-2.5 w-2.5 shrink-0 rounded-full ${item.status === "human_active" ? "bg-amber-500" : item.status === "ai_active" ? "bg-sky-500" : "bg-slate-400"}`} /></div><p className="mt-1 text-xs capitalize text-slate-500">{item.channel} · {new Date(item.updated_at).toLocaleDateString()}</p></Link>; })}</div></aside>
    <main className="min-w-0 space-y-4"><AuthMessage error={query.error} message={query.message} /><section className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div><div className="flex items-center gap-2"><h2 className="font-black">{String(lead?.name || "Website visitor")}</h2><span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${statusStyle[conversation.status]}`}>{conversation.status.replace("_", " ")}</span></div><p className="mt-1 text-xs text-slate-500">{conversation.status === "human_active" ? "Human active — AI waa hakad" : "AI ayaa jawaabaha maamulaya"}</p></div><form action={setConversationMode}><input name="conversation_id" type="hidden" value={conversation.id} /><input name="mode" type="hidden" value={conversation.status === "human_active" ? "ai_active" : "human_active"} /><button className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white">{conversation.status === "human_active" ? "Return to AI" : "Take over"}</button></form></section>
      {["owner", "admin", "manager"].includes(membership.role) ? <form action={assignConversation} className="flex flex-wrap items-end gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4"><input name="conversation_id" type="hidden" value={conversation.id} /><label className="min-w-56 flex-1 text-xs font-black text-amber-950">U xilsaar team member<select className="mt-2 w-full rounded-xl border border-amber-300 bg-white px-3 py-2.5 text-sm" defaultValue={conversation.assigned_agent_id ?? ""} name="member_id" required><option disabled value="">Dooro qof</option>{members?.map((member) => <option key={member.id} value={member.id}>{memberNameByUserId.get(member.user_id) || member.role} · {member.availability}</option>)}</select></label><button className="rounded-xl bg-amber-500 px-4 py-2.5 text-sm font-black">Assign &amp; pause AI</button></form> : null}
      <section className="max-h-[58vh] min-h-[28rem] space-y-4 overflow-y-auto rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7">{messages?.map((message) => <article className={`flex ${message.sender_type === "customer" ? "justify-start" : "justify-end"}`} key={message.id}><div className={`max-w-[82%] rounded-2xl px-4 py-3 ${message.sender_type === "customer" ? "bg-slate-100" : message.sender_type === "agent" ? "bg-slate-950 text-white" : "bg-emerald-500"}`}><p className="whitespace-pre-wrap text-sm leading-6">{message.message}</p><p className="mt-1 text-[10px] opacity-60">{message.sender_type} · {new Date(message.created_at).toLocaleString()}</p></div></article>)}</section>
      {conversation.status === "human_active" ? <form action={sendAgentMessage} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><input name="conversation_id" type="hidden" value={conversation.id} /><label className="text-sm font-bold text-slate-700">Agent reply<textarea className="mt-2 min-h-24 w-full rounded-xl border border-slate-300 p-3 text-sm" maxLength={4000} name="message" required /></label><button className="mt-3 rounded-xl bg-emerald-500 px-4 py-2.5 text-sm font-bold">Kaydi reply-ga</button></form> : <p className="rounded-2xl border border-sky-200 bg-sky-50 p-4 text-sm text-sky-800">Agent reply-ga waa xiran yahay inta AI active yahay. Guji Take over si aad uga jawaabto.</p>}
    </main>
    <aside className="space-y-4"><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black tracking-wide text-slate-400 uppercase">Lead context</p>{lead ? <div className="mt-4 space-y-3 text-sm">{[["Phone", lead.phone || "—"], ["Source", lead.source || conversation.channel], ["Purpose", lead.purpose || "—"], ["District", lead.district || "—"], ["Budget", lead.budget_min || lead.budget_max ? `$${Number(lead.budget_min ?? 0).toLocaleString()}–$${Number(lead.budget_max ?? 0).toLocaleString()}` : "—"], ["Bedrooms", lead.bedrooms ?? "—"], ["Status", lead.status || "—"]].map(([label, value]) => <div className="flex justify-between gap-3 border-b border-slate-100 pb-2" key={String(label)}><span className="text-slate-500">{label}</span><strong className="text-right capitalize">{String(value)}</strong></div>)}{conversation.lead_id ? <Link className="inline-flex font-bold text-emerald-700" href={`/leads/${conversation.lead_id}`}>Fur lead-ka →</Link> : null}</div> : <p className="mt-4 text-sm text-slate-500">Lead wali lama abuuri.</p>}</section>
      <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-black">Matched properties</h3><div className="mt-3 space-y-3">{matches.length ? matches.map((match) => <Link className="block rounded-xl bg-slate-50 p-3" href={`/properties/${match.property.id}`} key={match.property.id}><div className="flex justify-between gap-2"><span className="text-sm font-bold">{match.property.title}</span><span className="text-xs font-black text-emerald-700">{match.score}%</span></div><p className="mt-1 text-xs text-slate-500">{match.property.district} · ${Number(match.property.price).toLocaleString()}</p></Link>) : <p className="text-sm text-slate-500">Match lama helin.</p>}</div></section>
      <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-black">Viewings</h3><div className="mt-3 space-y-2">{viewings?.length ? viewings.map((viewing) => { const r = viewing.properties as { title?: string } | { title?: string }[] | null; const p = Array.isArray(r) ? r[0] : r; return <Link className="block rounded-xl bg-slate-50 p-3 text-xs" href={`/viewings/${viewing.id}`} key={viewing.id}><strong>{p?.title || "Property"}</strong><p className="mt-1 capitalize text-slate-500">{viewing.status} · {new Date(viewing.starts_at).toLocaleString()}</p></Link>; }) : <p className="text-sm text-slate-500">Viewing ma jiro.</p>}</div></section>
    </aside>
  </div></AppShell>;
}
